class CurrencyCatalog {
  const CurrencyCatalog._();

  static const popularCodes = <String>[
    'EUR',
    'USD',
    'GBP',
    'JPY',
    'CNY',
    'CAD',
    'AUD',
    'AED',
    'SAR',
    'MAD',
    'DZD',
    'BRL',
    'CVE',
  ];

  // Hardcoded labels so wording stays stable for i18n migration.
  static const _descriptionsFr = <String, String>{
    'AED': 'Dirham emirati (Emirats arabes unis)',
    'AFN': 'Afghani (Afghanistan)',
    'ALL': 'Lek albanais (Albanie)',
    'AMD': 'Dram armenien (Armenie)',
    'ANG': 'Florin antillais (Curaçao, Sint Maarten)',
    'AOA': 'Kwanza (Angola)',
    'ARS': 'Peso argentin (Argentine)',
    'AUD': 'Dollar australien (Australie)',
    'AWG': 'Florin arubais (Aruba)',
    'AZN': 'Manat azerbaidjanais (Azerbaidjan)',
    'BAM': 'Mark convertible (Bosnie-Herzegovine)',
    'BBD': 'Dollar barbadien (Barbade)',
    'BDT': 'Taka (Bangladesh)',
    'BGN': 'Lev bulgare (Bulgarie)',
    'BHD': 'Dinar bahreini (Bahrein)',
    'BMD': 'Dollar bermudien (Bermudes)',
    'BND': 'Dollar de Brunei (Brunei)',
    'BOB': 'Boliviano (Bolivie)',
    'BRL': 'Real bresilien (Bresil)',
    'BSD': 'Dollar bahameen (Bahamas)',
    'BWP': 'Pula (Botswana)',
    'BYN': 'Rouble bielorusse (Bielorussie)',
    'CAD': 'Dollar canadien (Canada)',
    'CHF': 'Franc suisse (Suisse)',
    'CLP': 'Peso chilien (Chili)',
    'CNY': 'Yuan renminbi (Chine)',
    'COP': 'Peso colombien (Colombie)',
    'CRC': 'Colon costaricien (Costa Rica)',
    'CZK': 'Couronne tcheque (Tchequie)',
    'DKK': 'Couronne danoise (Danemark)',
    'DOP': 'Peso dominicain (Republique dominicaine)',
    'DZD': 'Dinar algerien (Algerie)',
    'EGP': 'Livre egyptienne (Egypte)',
    'EUR': 'Euro (Zone euro)',
    'GBP': 'Livre sterling (Royaume-Uni)',
    'GHS': 'Cedi (Ghana)',
    'GTQ': 'Quetzal (Guatemala)',
    'HKD': 'Dollar de Hong Kong (Hong Kong)',
    'HUF': 'Forint (Hongrie)',
    'IDR': 'Roupie indonesienne (Indonesie)',
    'ILS': 'Shekel (Israel)',
    'INR': 'Roupie indienne (Inde)',
    'ISK': 'Couronne islandaise (Islande)',
    'JMD': 'Dollar jamaicain (Jamaique)',
    'JPY': 'Yen japonais (Japon)',
    'KES': 'Shilling kenyan (Kenya)',
    'KRW': 'Won sud-coreen (Coree du Sud)',
    'KWD': 'Dinar koweitien (Koweit)',
    'KZT': 'Tenge (Kazakhstan)',
    'LKR': 'Roupie srilankaise (Sri Lanka)',
    'MAD': 'Dirham marocain (Maroc)',
    'MDL': 'Leu moldave (Moldavie)',
    'MXN': 'Peso mexicain (Mexique)',
    'MYR': 'Ringgit (Malaisie)',
    'NGN': 'Naira (Nigeria)',
    'NOK': 'Couronne norvegienne (Norvege)',
    'NPR': 'Roupie nepalaise (Nepal)',
    'NZD': 'Dollar neo-zelandais (Nouvelle-Zelande)',
    'OMR': 'Rial omanais (Oman)',
    'PEN': 'Sol (Perou)',
    'PHP': 'Peso philippin (Philippines)',
    'PKR': 'Roupie pakistanaise (Pakistan)',
    'PLN': 'Zloty (Pologne)',
    'QAR': 'Riyal qatari (Qatar)',
    'RON': 'Leu roumain (Roumanie)',
    'RSD': 'Dinar serbe (Serbie)',
    'RUB': 'Rouble russe (Russie)',
    'SAR': 'Riyal saoudien (Arabie saoudite)',
    'SEK': 'Couronne suedoise (Suede)',
    'SGD': 'Dollar de Singapour (Singapour)',
    'THB': 'Baht (Thailande)',
    'TND': 'Dinar tunisien (Tunisie)',
    'TRY': 'Livre turque (Turquie)',
    'TWD': 'Dollar taiwanais (Taiwan)',
    'UAH': 'Hryvnia (Ukraine)',
    'USD': 'Dollar US (Etats-Unis)',
    'UYU': 'Peso uruguayen (Uruguay)',
    'UZS': 'Soum (Ouzbekistan)',
    'VND': 'Dong (Vietnam)',
    'XAF': 'Franc CFA BEAC (Afrique centrale)',
    'XOF': 'Franc CFA BCEAO (Afrique de l Ouest)',
    'ZAR': 'Rand (Afrique du Sud)',
    'ZMW': 'Kwacha zambien (Zambie)',
    'CVE': 'Escudo cap-verdien (Cap-Vert)',
  };

  static const _locales = <String, String>{
    'CHF': 'fr_CH',
    'EUR': 'fr_FR',
    'USD': 'en_US',
    'GBP': 'en_GB',
    'JPY': 'ja_JP',
    'CNY': 'zh_CN',
    'CAD': 'fr_CA',
    'AUD': 'en_AU',
    'AED': 'ar_AE',
    'SAR': 'ar_SA',
    'MAD': 'fr_MA',
    'DZD': 'fr_DZ',
    'BRL': 'pt_BR',
    'CVE': 'pt_CV',
    'ARS': 'es_AR',
    'MXN': 'es_MX',
    'NOK': 'nb_NO',
    'SEK': 'sv_SE',
    'PLN': 'pl_PL',
    'INR': 'en_IN',
    'TRY': 'tr_TR',
  };

  static String descriptionFr(String code) => _descriptionsFr[code] ?? code;

  static String labelFr(String code) {
    final description = descriptionFr(code);
    if (description == code) return code;
    return '$code - $description';
  }

  static String locale(String code) => _locales[code] ?? 'en_US';
}
